name:                GIT
version:             0.1.0.0
github:              "jdcarbeck/GIT"
license:             BSD3
author:              "John Carbeck"
maintainer:          "carbeckj@tcd.ie"
copyright:           "2018 John Carbeck"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/GIT#readme>

dependencies:
- base >= 4.7 && < 5
- github

library:
  source-dirs: src

executables:
  GIT-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GIT

tests:
  GIT-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GIT
