{-# LANGUAGE OverloadedStrings #-}

module Git where

import Network.Wreq
import Control.Lens
import Data.Aeson
import Data.Aeson.Lens
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import System.IO


--This must contain the username of the user using the api
userAgent :: B.ByteString
userAgent = B.pack "jdcarbeck"

--This must access the users github token generated by user
getToken :: IO B.ByteString
getToken = do
  token <- B.readFile "./githubToken.txt"
  return token

opts :: B.ByteString -> B.ByteString -> Network.Wreq.Options
opts usr token = defaults & header "Authorization" .~ [token]
                          & header "User-Agent" .~ [usr]

query = do
  token <- getToken
  r <- getWith (opts userAgent token) "https://api.github.com/users/jdcarbeck"
  print $ r ^. responseBody . key "repos_url" . _String
  print $ r ^? responseBody . key "id" . _Integer
  return Nothing

{-
TODO: At the moment I am able to take any token and user agent and create
a request and get back the information from the api, now I need
to pass in any url so the function can be called from anywhere

Need a data type that corresponds to the structure of a responseBody
Going to create data types for each of the respositories that I want to query and then
repositories


Idea github marking site that gives you a rating and then graphs you in a
distribution of users

{
  "login": "github",
  "id": 1,
  "node_id": "MDEyOk9yZ2FuaXphdGlvbjE=",
  "url": "https://api.github.com/orgs/github",
  "repos_url": "https://api.github.com/orgs/github/repos",
  "events_url": "https://api.github.com/orgs/github/events",
  "hooks_url": "https://api.github.com/orgs/github/hooks",
  "issues_url": "https://api.github.com/orgs/github/issues",
  "members_url": "https://api.github.com/orgs/github/members{/member}",
  "public_members_url": "https://api.github.com/orgs/github/public_members{/member}",
  "avatar_url": "https://github.com/images/error/octocat_happy.gif",
  "description": "A great organization",
  "name": "github",
  "company": "GitHub",
  "blog": "https://github.com/blog",
  "location": "San Francisco",
  "email": "octocat@github.com",
  "is_verified": true,
  "has_organization_projects": true,
  "has_repository_projects": true,
  "public_repos": 2,
  "public_gists": 1,
  "followers": 20,
  "following": 0,
  "html_url": "https://github.com/octocat",
  "created_at": "2008-01-14T04:33:35Z",
  "type": "Organization",
-}
