{-# LANGUAGE OverloadedStrings #-}

module Git where

import qualified Network.Wreq as Req
import Control.Lens
import Data.Aeson
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import System.IO

--This must contain the username of the user using the api
userAgent :: B.ByteString
userAgent = B.pack "jdcarbeck"

--This must access the users github token generated by user
getToken :: IO B.ByteString
getToken = do
  token <- B.readFile ".././githubToken.txt"
  return token

opts :: B.ByteString -> B.ByteString -> Req.Options
opts usr token = Req.defaults & Req.header "Authorization" .~ [token]
                          &  Req.header "User-Agent" .~ [usr]

query = do
  token <- getToken
  r <- Req.getWith (opts userAgent token) "https://api.github.com/users"
  return $ r ^? Req.responseBody

{-


At the moment I am able to take any token and user agent and create
a request and get back the information from the api, now I need
to pass in any url so the function can be called from anywhere
-}
