{-# LANGUAGE OverloadedStrings #-}

module Git where

import Network.HTTP.Conduit
import qualified Data.ByteString.Char8 as B
import System.IO

--This must contain the username of the user using the api
userAgent :: B.ByteString
userAgent = B.pack "jdcarbeck"

--This must access the users github token generated by user
getToken :: IO B.ByteString
getToken = do
  token <- B.readFile "./githubToken.txt"
  return token

httpWithUserAgent :: IO String
httpWithUserAgent = do
  --parse the url to r
  r <- parseUrlThrow "https://api.github.com/users"
  -- token generated by getToken function
  token <- getToken
  --make request with auth tokens and user agent
  let request = r {requestHeaders = [("User-Agent", userAgent)
                                     , ("Authorization", token)]}
  --tls manager added
  manager <- newManager tlsManagerSettings
  -- res is the calling off the request with manager
  res <- httpLbs request manager
  -- return the responseBodys
  return . show . responseBody $ res
